/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RefRouteImport } from './routes/ref'
import { Route as IndexRouteImport } from './routes/index'

const RefRoute = RefRouteImport.update({
  id: '/ref',
  path: '/ref',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ref': typeof RefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ref': typeof RefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ref': typeof RefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ref'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ref'
  id: '__root__' | '/' | '/ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RefRoute: typeof RefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ref': {
      id: '/ref'
      path: '/ref'
      fullPath: '/ref'
      preLoaderRoute: typeof RefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RefRoute: RefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
